common: &common
  endpoint: 'https://development.avalara.net'
  username: 'your username'
  password: 'your password'
  company_code: 'your company code'

test:
  <<: *common
development:
  <<: *common
production:
  <<: *common